# 将 NVIDIA RTX 2060 Mobile (10de:1f15) 及附属功能绑定到 vfio-pci 用于虚拟机直通
options vfio-pci ids=10de:1f15,10de:10f9,10de:1ada,10de:1adb
softdep nouveau pre: vfio-pci
softdep xhci_hcd pre: vfio-pci
softdep i2c_nvidia_gpu pre: vfio-pci
